name: Build and create release
on: 
  workflow_dispatch:
    inputs:
      release:
        description: 'Pre-release'
        required: false
        default: 'true'
      version:
        description: 'Version'
        required: true

permissions:
  contents: read

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Release level: ${{ github.event.inputs.releaseLevel }}"
        echo "Version: ${{ github.event.inputs.version }}" 


  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2.4.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.04
      - name: setup jdk 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Artifacts
          path: build/libs/
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: AutoModpack
          body: |
            AutoModpack
          draft: false
          prerelease: ${{ github.event.inputs.releaseLevel }}
          
#       - name: Create Release
#         uses: softprops/action-gh-release@v0.1.14

          
          
