name: Build and create release
on: 
  workflow_dispatch:
    inputs:
      release:
        description: 'PreRelease?'
        required: true
        type: choice
        options:
        - 'false'
        - 'true'
      version:
        description: 'Version'
        required: true
      automatic_release_tag:
        required: true


permissions:
  write-all

jobs:

  Build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Inputs
        shell: python
        run: |
          print("📝 PreRelease?: ${{ github.event.inputs.release }}\n🦿 Version: ${{ github.event.inputs.version }}\n🏷️ Automatic release tag: ${{ github.event.inputs.automatic_release_tag }}");
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.inputs.automatic_release_tag }}"
          prerelease: ${{ github.event.inputs.release }}
          title: "AutoModpack ${{ github.event.inputs.version }}"
          files: |
            ./build/libs/*.jar
