name: Build and create release
on: 
  workflow_dispatch:
    inputs:
      release:
        description: 'Release type'
        required: true
        type: choice
        options:
        - Prerelease
        - Release
      version:
        description: 'Version'
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Inputs
        shell: python
        run: |
          print("📝 Release type: ${{ github.event.inputs.release }}\n🦿 Version: ${{ github.event.inputs.version }}");
          if ${{ github.event.inputs.release }} = Release:
            type = false
          else:
            type = true
            
      - name: checkout repository
        uses: actions/checkout@v2.4.1
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: setup jdk 17
        uses: actions/setup-java@v3.1.1
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: build
        run: ./gradlew build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Artifacts
          path: build/libs/
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: AutoModpack
          body: |
            AutoModpack
          draft: false
          prerelease: ${{ env.type }}
          
          
          
#       - name: Create Release
#         uses: softprops/action-gh-release@v0.1.14

          
          
