name: Build and create release
on: 
  workflow_dispatch:
    inputs:
      release:
        description: 'Release type'
        required: true
        type: choice
        options:
        - PreRelease
        - Release
      version:
        description: 'Version'
        required: true


permissions:
  read, write-all

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Inputs
        shell: python
        run: |
          print("📝 Release type: ${{ github.event.inputs.release }}\n🦿 Version: ${{ github.event.inputs.version }}");
            
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
#           distribution: 'temurin'
          
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
          
        if: ${{ github.event.inputs.release }} == PreRelease
      - name: Create PreRelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "AutoModpack ${{ github.event.inputs.version }}"
          files: |
            ./build/libs/*.jar
          
        if: ${{ github.event.inputs.release }} == Release
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "AutoModpack ${{ github.event.inputs.version }}"
          files: |
            ./build/libs/*.jar
          
          
          
#       - name: Create Release
#         uses: softprops/action-gh-release@v0.1.14

          
          
